# Generated by Django 2.2.5 on 2020-01-10 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paperfeedback',
            old_name='description',
            new_name='description_1',
        ),
    ]
