# Generated by Django 2.2.5 on 2020-01-10 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200110_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paperfeedback',
            old_name='description_1',
            new_name='description_fb',
        ),
    ]
