from catalog.views.views import *
from catalog.views.views_people import *
from catalog.views.views_codes import *
from catalog.views.views_group import *
from catalog.views.views_collection import *
from catalog.views.views_comment import *
from catalog.views.views_dataset import *
from catalog.views.views_endorsement import *
from catalog.views.views_profile import *
from catalog.views.views_moderation import *
