from catalog.tests.test_author_model import *
from catalog.tests.test_author_views import *
from catalog.tests.test_venue_model import *
from catalog.tests.test_venue_views import *
from catalog.tests.test_dataset_model import *
from catalog.tests.test_dataset_views import *
from catalog.tests.test_code_model import *
from catalog.tests.test_code_views import *
from catalog.tests.test_group_views import *
